import React from 'react';
import Input from './components/ui/Input';
import Button from './components/ui/Button';

export default function Component() {
  return (
    <div key="1" className="max-w-3xl mx-auto p-8">
      <div className="flex h-screen justify-center">
        <div className="w-64 bg-gray-100 p-4 rounded-lg shadow-md">
          <h2 className="text-lg font-semibold mb-4">Stored Recipes</h2>
          <ul className="space-y-2">
            <li className="bg-white p-2 rounded shadow hover:bg-gray-50 transition-colors">
              <div>
                <a className="text-gray-700 font-medium" href="#">
                  Chicken Parmesan
                </a>
              </div>
            </li>
            <li className="bg-white p-2 rounded shadow hover:bg-gray-50 transition-colors">
              <a className="text-gray-700 font-medium" href="#">
                Beef Tacos
              </a>
            </li>
            <li className="bg-white p-2 rounded shadow hover:bg-gray-50 transition-colors">
              <a className="text-gray-700 font-medium" href="#">
                Vegetable Stir-Fry
              </a>
            </li>
          </ul>
        </div>
        <div className="flex-1 bg-gray-50 p-6 rounded-lg shadow-md ml-4">
          <div className="text-center mb-6">
            <h1 className="text-3xl font-bold">Recipe AI</h1>
            <p className="text-gray-600 mt-2">Get recipes generated by our AI based on your requests.</p>
          </div>
          <div />
          <div className="bg-white p-4 shadow rounded mb-4 h-64 overflow-auto">
            <p className="text-gray-700">This is a response box for the AI, not a list of items.</p>
          </div>
          <div className="flex">
            <Input className="flex-1 mr-2 rounded-md shadow-sm" placeholder="Request a new recipe" />
            <Button className="rounded-md shadow-sm">Generate</Button>
          </div>
        </div>
      </div>
    </div>
  )
}